USE todoapp;

CREATE TABLE Todos (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Title VARCHAR(200) NOT NULL,
	Description TEXT NOT NULL,
	Status INT NOT NULL DEFAULT 0,
	Deadline DATE NULL,
	
	CONSTRAINT CK_Todos_Status
	   CHECK (Status IN (0, 1, 2))
) DEFAULT CHARACTER SET utf8mb4;